//#############AUTOGENERATED##########
#include "fcsModel_types.h"


busFcsParams AssignFcsCtrlParams(){
	busFcsParams fcs_ctrl_params;
	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[0].Kp = 1.20000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[0].Ki = 0.01000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[0].Kd = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[0].Kb = 0.08200000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[0].Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[0].filterBandwidth_radps = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[0].outputLimits[0] = -6.28318531;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[0].outputLimits[1] = 6.28318531;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[0].outputRateLimits[0] = -1570.79632679;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[0].outputRateLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[1].Kp = 1.70000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[1].Ki = 0.01000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[1].Kd = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[1].Kb = 0.07500000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[1].Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[1].filterBandwidth_radps = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[1].outputLimits[0] = -6.28318531;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[1].outputLimits[1] = 6.28318531;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[1].outputRateLimits[0] = -1570.79632679;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[1].outputRateLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[2].Kp = 1.50000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[2].Ki = 0.02000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[2].Kd = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[2].Kb = 0.08200000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[2].Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[2].filterBandwidth_radps = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[2].outputLimits[0] = -6.28318531;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[2].outputLimits[1] = 6.28318531;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[2].outputRateLimits[0] = -1570.79632679;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.ctrlParamsArray[2].outputRateLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputLimits[0] = -0.78539816;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputLimits[1] = 0.78539816;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputRateLimits[0] = -196.34954085;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputRateLimits[1] = 196.34954085;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputAccelLimits[0] = -49087.38521234;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputAccelLimits[1] = 49087.38521234;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputJerkLimits[0] = -12271846.30308513;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputJerkLimits[1] = 12271846.30308513;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[0].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[0].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputLimits[0] = -0.78539816;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputLimits[1] = 0.78539816;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputRateLimits[0] = -196.34954085;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputRateLimits[1] = 196.34954085;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputAccelLimits[0] = -49087.38521234;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputAccelLimits[1] = 49087.38521234;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputJerkLimits[0] = -12271846.30308513;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputJerkLimits[1] = 12271846.30308513;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[1].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[1].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputLimits[0] = -3.12413936;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputLimits[1] = 3.14159265;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputRateLimits[0] = -196.34954085;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputRateLimits[1] = 196.34954085;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputAccelLimits[0] = -49087.38521234;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputAccelLimits[1] = 49087.38521234;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputJerkLimits[0] = -12271846.30308513;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputJerkLimits[1] = 12271846.30308513;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[2].filterParams.filterBandwidth_radps = 25.13274123;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.cmdSignalConditioningParamsArray[2].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[0].filteredInputLimits[0] = -15.70796327;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[0].filteredInputLimits[1] = 15.70796327;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[0].filteredInputRateLimits[0] = -3926.99081699;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[0].filteredInputRateLimits[1] = 3926.99081699;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[0].filteredInputAccelLimits[0] = -981747.70424681;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[0].filteredInputAccelLimits[1] = 981747.70424681;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[0].filteredInputJerkLimits[0] = -245436926.06170261;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[0].filteredInputJerkLimits[1] = 245436926.06170261;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[0].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[0].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[1].filteredInputLimits[0] = -15.70796327;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[1].filteredInputLimits[1] = 15.70796327;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[1].filteredInputRateLimits[0] = -3926.99081699;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[1].filteredInputRateLimits[1] = 3926.99081699;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[1].filteredInputAccelLimits[0] = -981747.70424681;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[1].filteredInputAccelLimits[1] = 981747.70424681;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[1].filteredInputJerkLimits[0] = -245436926.06170261;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[1].filteredInputJerkLimits[1] = 245436926.06170261;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[1].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[1].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[2].filteredInputLimits[0] = -3.12413936;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[2].filteredInputLimits[1] = 3.14159265;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[2].filteredInputRateLimits[0] = -3926.99081699;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[2].filteredInputRateLimits[1] = 3926.99081699;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[2].filteredInputAccelLimits[0] = -981747.70424681;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[2].filteredInputAccelLimits[1] = 981747.70424681;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[2].filteredInputJerkLimits[0] = -245436926.06170261;
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[2].filteredInputJerkLimits[1] = 245436926.06170261;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[2].filterParams.filterBandwidth_radps = 25.13274123;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.attCtrlParams.measSignalConditioningParamsArray[2].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[0].Kp = 22.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[0].Ki = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[0].Kd = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[0].Kb = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[0].Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[0].filterBandwidth_radps = 188.49555922;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[0].outputLimits[0] = -1570.79632679;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[0].outputLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[0].outputRateLimits[0] = -392699.08169872;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[0].outputRateLimits[1] = 392699.08169872;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[1].Kp = 28.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[1].Ki = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[1].Kd = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[1].Kb = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[1].Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[1].filterBandwidth_radps = 188.49555922;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[1].outputLimits[0] = -1570.79632679;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[1].outputLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[1].outputRateLimits[0] = -392699.08169872;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[1].outputRateLimits[1] = 392699.08169872;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[2].Kp = 30.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[2].Ki = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[2].Kd = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[2].Kb = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[2].Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[2].filterBandwidth_radps = 188.49555922;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[2].outputLimits[0] = -1570.79632679;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[2].outputLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[2].outputRateLimits[0] = -392699.08169872;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.ctrlParamsArray[2].outputRateLimits[1] = 392699.08169872;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputLimits[0] = -6.28318531;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputLimits[1] = 6.28318531;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputRateLimits[0] = -1570.79632679;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputRateLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputAccelLimits[0] = -392699.08169872;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputAccelLimits[1] = 392699.08169872;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputJerkLimits[0] = -98174770.42468102;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputJerkLimits[1] = 98174770.42468102;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputLimits[0] = -6.28318531;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputLimits[1] = 6.28318531;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputRateLimits[0] = -1570.79632679;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputRateLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputAccelLimits[0] = -392699.08169872;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputAccelLimits[1] = 392699.08169872;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputJerkLimits[0] = -98174770.42468102;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputJerkLimits[1] = 98174770.42468102;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputLimits[0] = -6.28318531;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputLimits[1] = 6.28318531;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputRateLimits[0] = -1570.79632679;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputRateLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputAccelLimits[0] = -392699.08169872;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputAccelLimits[1] = 392699.08169872;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputJerkLimits[0] = -98174770.42468102;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputJerkLimits[1] = 98174770.42468102;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filterParams.filterBandwidth_radps = 50.26548246;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[0].filteredInputLimits[0] = -125.66370614;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[0].filteredInputLimits[1] = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[0].filteredInputRateLimits[0] = -31415.92653590;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[0].filteredInputRateLimits[1] = 31415.92653590;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[0].filteredInputAccelLimits[0] = -7853981.63397448;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[0].filteredInputAccelLimits[1] = 7853981.63397448;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[0].filteredInputJerkLimits[0] = -1963495408.49362087;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[0].filteredInputJerkLimits[1] = 1963495408.49362087;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[0].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[0].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[1].filteredInputLimits[0] = -125.66370614;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[1].filteredInputLimits[1] = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[1].filteredInputRateLimits[0] = -31415.92653590;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[1].filteredInputRateLimits[1] = 31415.92653590;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[1].filteredInputAccelLimits[0] = -7853981.63397448;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[1].filteredInputAccelLimits[1] = 7853981.63397448;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[1].filteredInputJerkLimits[0] = -1963495408.49362087;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[1].filteredInputJerkLimits[1] = 1963495408.49362087;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[1].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[1].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[2].filteredInputLimits[0] = -125.66370614;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[2].filteredInputLimits[1] = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[2].filteredInputRateLimits[0] = -31415.92653590;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[2].filteredInputRateLimits[1] = 31415.92653590;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[2].filteredInputAccelLimits[0] = -7853981.63397448;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[2].filteredInputAccelLimits[1] = 7853981.63397448;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[2].filteredInputJerkLimits[0] = -1963495408.49362087;
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[2].filteredInputJerkLimits[1] = 1963495408.49362087;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[2].filterParams.filterBandwidth_radps = 50.26548246;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.innerLoopCtrlParams.angRateCtrlParams.measSignalConditioningParamsArray[2].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[0].Kp = 0.07500000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[0].Ki = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[0].Kd = 0.06000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[0].Kb = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[0].Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[0].filterBandwidth_radps = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[0].outputLimits[0] = -2.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[0].outputLimits[1] = 2.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[0].outputRateLimits[0] = -100.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[0].outputRateLimits[1] = 100.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[1].Kp = 0.07500000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[1].Ki = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[1].Kd = 0.06000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[1].Kb = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[1].Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[1].filterBandwidth_radps = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[1].outputLimits[0] = -2.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[1].outputLimits[1] = 2.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[1].outputRateLimits[0] = -100.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[1].outputRateLimits[1] = 100.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[2].Kp = 0.15000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[2].Ki = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[2].Kd = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[2].Kb = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[2].Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[2].filterBandwidth_radps = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[2].outputLimits[0] = -2.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[2].outputLimits[1] = 2.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[2].outputRateLimits[0] = -100.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.ctrlParamsArray[2].outputRateLimits[1] = 100.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputLimits[0] = -1000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputLimits[1] = 1000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputRateLimits[0] = -50000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputRateLimits[1] = 50000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputAccelLimits[0] = -2500000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputAccelLimits[1] = 2500000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputJerkLimits[0] = -125000000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputJerkLimits[1] = 125000000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[0].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[0].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputLimits[0] = -1000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputLimits[1] = 1000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputRateLimits[0] = -50000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputRateLimits[1] = 50000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputAccelLimits[0] = -2500000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputAccelLimits[1] = 2500000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputJerkLimits[0] = -125000000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputJerkLimits[1] = 125000000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[1].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[1].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputLimits[0] = -1000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputLimits[1] = 1000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputRateLimits[0] = -50000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputRateLimits[1] = 50000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputAccelLimits[0] = -2500000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputAccelLimits[1] = 2500000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputJerkLimits[0] = -125000000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputJerkLimits[1] = 125000000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[2].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.cmdSignalConditioningParamsArray[2].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[0].filteredInputLimits[0] = -100000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[0].filteredInputLimits[1] = 100000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[0].filteredInputRateLimits[0] = -5000000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[0].filteredInputRateLimits[1] = 5000000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[0].filteredInputAccelLimits[0] = -250000000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[0].filteredInputAccelLimits[1] = 250000000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[0].filteredInputJerkLimits[0] = -12500000000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[0].filteredInputJerkLimits[1] = 12500000000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[0].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[0].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[1].filteredInputLimits[0] = -100000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[1].filteredInputLimits[1] = 100000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[1].filteredInputRateLimits[0] = -5000000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[1].filteredInputRateLimits[1] = 5000000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[1].filteredInputAccelLimits[0] = -250000000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[1].filteredInputAccelLimits[1] = 250000000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[1].filteredInputJerkLimits[0] = -12500000000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[1].filteredInputJerkLimits[1] = 12500000000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[1].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[1].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[2].filteredInputLimits[0] = -100000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[2].filteredInputLimits[1] = 100000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[2].filteredInputRateLimits[0] = -5000000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[2].filteredInputRateLimits[1] = 5000000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[2].filteredInputAccelLimits[0] = -250000000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[2].filteredInputAccelLimits[1] = 250000000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[2].filteredInputJerkLimits[0] = -12500000000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[2].filteredInputJerkLimits[1] = 12500000000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[2].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.posCtrlParams.measSignalConditioningParamsArray[2].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[0].Kp = 0.75000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[0].Ki = 0.07500000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[0].Kd = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[0].Kb = 0.32000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[0].Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[0].filterBandwidth_radps = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[0].outputLimits[0] = -5.44500000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[0].outputLimits[1] = 5.44500000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[0].outputRateLimits[0] = -272.25000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[0].outputRateLimits[1] = 272.25000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[1].Kp = 0.75000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[1].Ki = 0.07500000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[1].Kd = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[1].Kb = 0.32000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[1].Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[1].filterBandwidth_radps = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[1].outputLimits[0] = -5.44500000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[1].outputLimits[1] = 5.44500000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[1].outputRateLimits[0] = -272.25000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[1].outputRateLimits[1] = 272.25000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[2].Kp = 0.80000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[2].Ki = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[2].Kd = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[2].Kb = 0.32000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[2].Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[2].filterBandwidth_radps = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[2].outputLimits[0] = -4.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[2].outputLimits[1] = 4.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[2].outputRateLimits[0] = -200.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ctrlParamsArray[2].outputRateLimits[1] = 200.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputLimits[0] = -2.50000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputLimits[1] = 2.50000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputRateLimits[0] = -125.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputRateLimits[1] = 125.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputAccelLimits[0] = -6250.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputAccelLimits[1] = 6250.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputJerkLimits[0] = -312500.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputJerkLimits[1] = 312500.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[0].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[0].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputLimits[0] = -2.50000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputLimits[1] = 2.50000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputRateLimits[0] = -125.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputRateLimits[1] = 125.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputAccelLimits[0] = -6250.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputAccelLimits[1] = 6250.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputJerkLimits[0] = -312500.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputJerkLimits[1] = 312500.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[1].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[1].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputLimits[0] = -2.50000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputLimits[1] = 2.50000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputRateLimits[0] = -125.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputRateLimits[1] = 125.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputAccelLimits[0] = -6250.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputAccelLimits[1] = 6250.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputJerkLimits[0] = -312500.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputJerkLimits[1] = 312500.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[2].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.cmdSignalConditioningParamsArray[2].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[0].filteredInputLimits[0] = -250.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[0].filteredInputLimits[1] = 250.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[0].filteredInputRateLimits[0] = -12500.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[0].filteredInputRateLimits[1] = 12500.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[0].filteredInputAccelLimits[0] = -625000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[0].filteredInputAccelLimits[1] = 625000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[0].filteredInputJerkLimits[0] = -31250000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[0].filteredInputJerkLimits[1] = 31250000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[0].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[0].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[1].filteredInputLimits[0] = -250.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[1].filteredInputLimits[1] = 250.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[1].filteredInputRateLimits[0] = -12500.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[1].filteredInputRateLimits[1] = 12500.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[1].filteredInputAccelLimits[0] = -625000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[1].filteredInputAccelLimits[1] = 625000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[1].filteredInputJerkLimits[0] = -31250000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[1].filteredInputJerkLimits[1] = 31250000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[1].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[1].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[2].filteredInputLimits[0] = -250.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[2].filteredInputLimits[1] = 250.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[2].filteredInputRateLimits[0] = -12500.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[2].filteredInputRateLimits[1] = 12500.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[2].filteredInputAccelLimits[0] = -625000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[2].filteredInputAccelLimits[1] = 625000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[2].filteredInputJerkLimits[0] = -31250000.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[2].filteredInputJerkLimits[1] = 31250000.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[2].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.measSignalConditioningParamsArray[2].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[0].filteredInputLimits[0] = -98.10000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[0].filteredInputLimits[1] = 98.10000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[0].filteredInputRateLimits[0] = -4905.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[0].filteredInputRateLimits[1] = 4905.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[0].filteredInputAccelLimits[0] = -245250.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[0].filteredInputAccelLimits[1] = 245250.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[0].filteredInputJerkLimits[0] = -12262500.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[0].filteredInputJerkLimits[1] = 12262500.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[0].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[0].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[1].filteredInputLimits[0] = -98.10000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[1].filteredInputLimits[1] = 98.10000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[1].filteredInputRateLimits[0] = -4905.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[1].filteredInputRateLimits[1] = 4905.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[1].filteredInputAccelLimits[0] = -245250.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[1].filteredInputAccelLimits[1] = 245250.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[1].filteredInputJerkLimits[0] = -12262500.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[1].filteredInputJerkLimits[1] = 12262500.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[1].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[1].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[2].filteredInputLimits[0] = -98.10000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[2].filteredInputLimits[1] = 98.10000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[2].filteredInputRateLimits[0] = -4905.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[2].filteredInputRateLimits[1] = 4905.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[2].filteredInputAccelLimits[0] = -245250.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[2].filteredInputAccelLimits[1] = 245250.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[2].filteredInputJerkLimits[0] = -12262500.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[2].filteredInputJerkLimits[1] = 12262500.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[2].filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelSignalConditioningParamsArray[2].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelFbGainsArray[0] = 0.10000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelFbGainsArray[1] = 0.10000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelFbGainsArray[2] = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ffGainsArray[0] = 0.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ffGainsArray[1] = 0.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.ffGainsArray[2] = 2.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.baseMass_kg = 2.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.baseMassMinMax_kg[0] = 1.50000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.baseMassMinMax_kg[1] = 3.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelCmdToAttitudeCmdScale_nd[0] = 1.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.velCtrlParams.accelCmdToAttitudeCmdScale_nd[1] = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.ctrlParams.Kp = 1.30000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.ctrlParams.Ki = 0.27500000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.ctrlParams.Kd = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.ctrlParams.Kb = 0.70000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.ctrlParams.Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.ctrlParams.filterBandwidth_radps = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.ctrlParams.outputLimits[0] = -5.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.ctrlParams.outputLimits[1] = 5.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.ctrlParams.outputRateLimits[0] = -250.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.ctrlParams.outputRateLimits[1] = 250.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.cmdSignalConditioningParams.filteredInputLimits[0] = -98.10000000;
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.cmdSignalConditioningParams.filteredInputLimits[1] = 98.10000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.cmdSignalConditioningParams.filteredInputRateLimits[0] = -4905.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.cmdSignalConditioningParams.filteredInputRateLimits[1] = 4905.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.cmdSignalConditioningParams.filteredInputAccelLimits[0] = -245250.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.cmdSignalConditioningParams.filteredInputAccelLimits[1] = 245250.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.cmdSignalConditioningParams.filteredInputJerkLimits[0] = -12262500.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.cmdSignalConditioningParams.filteredInputJerkLimits[1] = 12262500.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.cmdSignalConditioningParams.filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.cmdSignalConditioningParams.filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.measSignalConditioningParams.filteredInputLimits[0] = -98.10000000;
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.measSignalConditioningParams.filteredInputLimits[1] = 98.10000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.measSignalConditioningParams.filteredInputRateLimits[0] = -4905.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.measSignalConditioningParams.filteredInputRateLimits[1] = 4905.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.measSignalConditioningParams.filteredInputAccelLimits[0] = -245250.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.measSignalConditioningParams.filteredInputAccelLimits[1] = 245250.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.measSignalConditioningParams.filteredInputJerkLimits[0] = -12262500.00000000;
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.measSignalConditioningParams.filteredInputJerkLimits[1] = 12262500.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.measSignalConditioningParams.filterParams.filterBandwidth_radps = 471.23889804;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.measSignalConditioningParams.filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.outerLoopCtrlParams.zAccelCtrlParams.ffGain = 1.00000000;
	//#################################################*

	return fcs_ctrl_params;
}
