//#############AUTOGENERATED##########
#include "fcsModel_types.h"


#define RPM_TO_PWM_SCALE 0.17964912


busInnerLoopCtrlParams fcs_ctrl_params;


void AssignFcsCtrlParams(){
	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[0].Kp = 1.50000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[0].Ki = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[0].Kd = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[0].Kb = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[0].Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[0].filterBandwidth_radps = 628.31853072;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[0].outputLimits[0] = -6.28318531;
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[0].outputLimits[1] = 6.28318531;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[0].outputRateLimits[0] = -1570.79632679;
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[0].outputRateLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[1].Kp = 1.80000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[1].Ki = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[1].Kd = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[1].Kb = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[1].Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[1].filterBandwidth_radps = 628.31853072;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[1].outputLimits[0] = -6.28318531;
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[1].outputLimits[1] = 6.28318531;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[1].outputRateLimits[0] = -1570.79632679;
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[1].outputRateLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[2].Kp = 1.50000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[2].Ki = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[2].Kd = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[2].Kb = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[2].Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[2].filterBandwidth_radps = 628.31853072;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[2].outputLimits[0] = -6.28318531;
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[2].outputLimits[1] = 6.28318531;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[2].outputRateLimits[0] = -1570.79632679;
	fcs_ctrl_params.attCtrlParams.ctrlParamsArray[2].outputRateLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputLimits[0] = -6.28318531;
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputLimits[1] = 6.28318531;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputRateLimits[0] = -1570.79632679;
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputRateLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputAccelLimits[0] = -392699.08169872;
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputAccelLimits[1] = 392699.08169872;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputJerkLimits[0] = -98174770.42468102;
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputJerkLimits[1] = 98174770.42468102;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[0].filterParams.filterBandwidth_radps = 31.41592654;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[0].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputLimits[0] = -6.28318531;
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputLimits[1] = 6.28318531;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputRateLimits[0] = -1570.79632679;
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputRateLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputAccelLimits[0] = -392699.08169872;
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputAccelLimits[1] = 392699.08169872;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputJerkLimits[0] = -98174770.42468102;
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputJerkLimits[1] = 98174770.42468102;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[1].filterParams.filterBandwidth_radps = 31.41592654;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[1].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputLimits[0] = -6.28318531;
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputLimits[1] = 6.28318531;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputRateLimits[0] = -1570.79632679;
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputRateLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputAccelLimits[0] = -392699.08169872;
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputAccelLimits[1] = 392699.08169872;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputJerkLimits[0] = -98174770.42468102;
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputJerkLimits[1] = 98174770.42468102;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[2].filterParams.filterBandwidth_radps = 31.41592654;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.cmdSignalConditioningParamsArray[2].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[0].filteredInputLimits[0] = -125.66370614;
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[0].filteredInputLimits[1] = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[0].filteredInputRateLimits[0] = -31415.92653590;
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[0].filteredInputRateLimits[1] = 31415.92653590;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[0].filteredInputAccelLimits[0] = -7853981.63397448;
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[0].filteredInputAccelLimits[1] = 7853981.63397448;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[0].filteredInputJerkLimits[0] = -1963495408.49362087;
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[0].filteredInputJerkLimits[1] = 1963495408.49362087;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[0].filterParams.filterBandwidth_radps = 94.24777961;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[0].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[1].filteredInputLimits[0] = -125.66370614;
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[1].filteredInputLimits[1] = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[1].filteredInputRateLimits[0] = -31415.92653590;
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[1].filteredInputRateLimits[1] = 31415.92653590;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[1].filteredInputAccelLimits[0] = -7853981.63397448;
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[1].filteredInputAccelLimits[1] = 7853981.63397448;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[1].filteredInputJerkLimits[0] = -1963495408.49362087;
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[1].filteredInputJerkLimits[1] = 1963495408.49362087;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[1].filterParams.filterBandwidth_radps = 94.24777961;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[1].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[2].filteredInputLimits[0] = -125.66370614;
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[2].filteredInputLimits[1] = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[2].filteredInputRateLimits[0] = -31415.92653590;
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[2].filteredInputRateLimits[1] = 31415.92653590;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[2].filteredInputAccelLimits[0] = -7853981.63397448;
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[2].filteredInputAccelLimits[1] = 7853981.63397448;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[2].filteredInputJerkLimits[0] = -1963495408.49362087;
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[2].filteredInputJerkLimits[1] = 1963495408.49362087;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[2].filterParams.filterBandwidth_radps = 94.24777961;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.attCtrlParams.measSignalConditioningParamsArray[2].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[0].Kp = 30.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[0].Ki = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[0].Kd = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[0].Kb = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[0].Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[0].filterBandwidth_radps = 628.31853072;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[0].outputLimits[0] = -1570.79632679;
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[0].outputLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[0].outputRateLimits[0] = -392699.08169872;
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[0].outputRateLimits[1] = 392699.08169872;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[1].Kp = 45.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[1].Ki = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[1].Kd = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[1].Kb = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[1].Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[1].filterBandwidth_radps = 628.31853072;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[1].outputLimits[0] = -1570.79632679;
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[1].outputLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[1].outputRateLimits[0] = -392699.08169872;
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[1].outputRateLimits[1] = 392699.08169872;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[2].Kp = 45.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[2].Ki = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[2].Kd = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[2].Kb = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[2].Kt = 0.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[2].filterBandwidth_radps = 628.31853072;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[2].outputLimits[0] = -1570.79632679;
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[2].outputLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[2].outputRateLimits[0] = -392699.08169872;
	fcs_ctrl_params.angRateCtrlParams.ctrlParamsArray[2].outputRateLimits[1] = 392699.08169872;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputLimits[0] = -6.28318531;
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputLimits[1] = 6.28318531;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputRateLimits[0] = -1570.79632679;
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputRateLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputAccelLimits[0] = -392699.08169872;
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputAccelLimits[1] = 392699.08169872;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputJerkLimits[0] = -98174770.42468102;
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filteredInputJerkLimits[1] = 98174770.42468102;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filterParams.filterBandwidth_radps = 94.24777961;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[0].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputLimits[0] = -6.28318531;
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputLimits[1] = 6.28318531;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputRateLimits[0] = -1570.79632679;
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputRateLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputAccelLimits[0] = -392699.08169872;
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputAccelLimits[1] = 392699.08169872;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputJerkLimits[0] = -98174770.42468102;
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filteredInputJerkLimits[1] = 98174770.42468102;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filterParams.filterBandwidth_radps = 94.24777961;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[1].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputLimits[0] = -6.28318531;
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputLimits[1] = 6.28318531;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputRateLimits[0] = -1570.79632679;
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputRateLimits[1] = 1570.79632679;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputAccelLimits[0] = -392699.08169872;
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputAccelLimits[1] = 392699.08169872;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputJerkLimits[0] = -98174770.42468102;
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filteredInputJerkLimits[1] = 98174770.42468102;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filterParams.filterBandwidth_radps = 94.24777961;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.cmdSignalConditioningParamsArray[2].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[0].filteredInputLimits[0] = -125.66370614;
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[0].filteredInputLimits[1] = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[0].filteredInputRateLimits[0] = -31415.92653590;
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[0].filteredInputRateLimits[1] = 31415.92653590;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[0].filteredInputAccelLimits[0] = -7853981.63397448;
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[0].filteredInputAccelLimits[1] = 7853981.63397448;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[0].filteredInputJerkLimits[0] = -1963495408.49362087;
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[0].filteredInputJerkLimits[1] = 1963495408.49362087;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[0].filterParams.filterBandwidth_radps = 314.15926536;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[0].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[1].filteredInputLimits[0] = -125.66370614;
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[1].filteredInputLimits[1] = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[1].filteredInputRateLimits[0] = -31415.92653590;
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[1].filteredInputRateLimits[1] = 31415.92653590;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[1].filteredInputAccelLimits[0] = -7853981.63397448;
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[1].filteredInputAccelLimits[1] = 7853981.63397448;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[1].filteredInputJerkLimits[0] = -1963495408.49362087;
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[1].filteredInputJerkLimits[1] = 1963495408.49362087;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[1].filterParams.filterBandwidth_radps = 314.15926536;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[1].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[2].filteredInputLimits[0] = -125.66370614;
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[2].filteredInputLimits[1] = 125.66370614;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[2].filteredInputRateLimits[0] = -31415.92653590;
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[2].filteredInputRateLimits[1] = 31415.92653590;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[2].filteredInputAccelLimits[0] = -7853981.63397448;
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[2].filteredInputAccelLimits[1] = 7853981.63397448;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[2].filteredInputJerkLimits[0] = -1963495408.49362087;
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[2].filteredInputJerkLimits[1] = 1963495408.49362087;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[2].filterParams.filterBandwidth_radps = 314.15926536;
	//#################################################*

	//**************************************************
	fcs_ctrl_params.angRateCtrlParams.measSignalConditioningParamsArray[2].filterParams.dampingRatio_nd = 1.00000000;
	//#################################################*

}
