//#############AUTOGENERATED##########
#include<fcs_out_data.h>

void AssignFcsData(const FcsOutput &fcs_output, DataFields data_to_save[], size_t data_index){

	data_to_save[data_index].actuator_cmds[0] = fcs_output.actuatorsCmds[0];
	data_to_save[data_index].actuator_cmds[1] = fcs_output.actuatorsCmds[1];
	data_to_save[data_index].actuator_cmds[2] = fcs_output.actuatorsCmds[2];
	data_to_save[data_index].actuator_cmds[3] = fcs_output.actuatorsCmds[3];

	data_to_save[data_index].fcsOut0 = fcs_output.fcsDebug.innerLoopCtrldebug.angRateCtrlDebug[0].output;
	data_to_save[data_index].fcsOut1 = fcs_output.fcsDebug.innerLoopCtrldebug.angRateCtrlDebug[0].proportionalOutput;
	data_to_save[data_index].fcsOut2 = fcs_output.fcsDebug.innerLoopCtrldebug.angRateCtrlDebug[0].integralOutput;
	data_to_save[data_index].fcsOut3 = fcs_output.fcsDebug.innerLoopCtrldebug.angRateCtrlDebug[0].derivativeOutput;
	data_to_save[data_index].fcsOut4 = fcs_output.fcsDebug.innerLoopCtrldebug.angRateCtrlDebug[1].output;
	data_to_save[data_index].fcsOut5 = fcs_output.fcsDebug.innerLoopCtrldebug.angRateCtrlDebug[1].proportionalOutput;
	data_to_save[data_index].fcsOut6 = fcs_output.fcsDebug.innerLoopCtrldebug.angRateCtrlDebug[1].integralOutput;
	data_to_save[data_index].fcsOut7 = fcs_output.fcsDebug.innerLoopCtrldebug.angRateCtrlDebug[1].derivativeOutput;
	data_to_save[data_index].fcsOut8 = fcs_output.fcsDebug.innerLoopCtrldebug.angRateCtrlDebug[2].output;
	data_to_save[data_index].fcsOut9 = fcs_output.fcsDebug.innerLoopCtrldebug.angRateCtrlDebug[2].proportionalOutput;
	data_to_save[data_index].fcsOut10 = fcs_output.fcsDebug.innerLoopCtrldebug.angRateCtrlDebug[2].integralOutput;
	data_to_save[data_index].fcsOut11 = fcs_output.fcsDebug.innerLoopCtrldebug.angRateCtrlDebug[2].derivativeOutput;
	data_to_save[data_index].fcsOut12 = fcs_output.fcsDebug.innerLoopCtrldebug.attCtrlDebug[0].output;
	data_to_save[data_index].fcsOut13 = fcs_output.fcsDebug.innerLoopCtrldebug.attCtrlDebug[0].proportionalOutput;
	data_to_save[data_index].fcsOut14 = fcs_output.fcsDebug.innerLoopCtrldebug.attCtrlDebug[0].integralOutput;
	data_to_save[data_index].fcsOut15 = fcs_output.fcsDebug.innerLoopCtrldebug.attCtrlDebug[0].derivativeOutput;
	data_to_save[data_index].fcsOut16 = fcs_output.fcsDebug.innerLoopCtrldebug.attCtrlDebug[1].output;
	data_to_save[data_index].fcsOut17 = fcs_output.fcsDebug.innerLoopCtrldebug.attCtrlDebug[1].proportionalOutput;
	data_to_save[data_index].fcsOut18 = fcs_output.fcsDebug.innerLoopCtrldebug.attCtrlDebug[1].integralOutput;
	data_to_save[data_index].fcsOut19 = fcs_output.fcsDebug.innerLoopCtrldebug.attCtrlDebug[1].derivativeOutput;
	data_to_save[data_index].fcsOut20 = fcs_output.fcsDebug.innerLoopCtrldebug.attCtrlDebug[2].output;
	data_to_save[data_index].fcsOut21 = fcs_output.fcsDebug.innerLoopCtrldebug.attCtrlDebug[2].proportionalOutput;
	data_to_save[data_index].fcsOut22 = fcs_output.fcsDebug.innerLoopCtrldebug.attCtrlDebug[2].integralOutput;
	data_to_save[data_index].fcsOut23 = fcs_output.fcsDebug.innerLoopCtrldebug.attCtrlDebug[2].derivativeOutput;
	data_to_save[data_index].fcsOut24 = static_cast<float>(fcs_output.fcsDebug.state);
}