//#############AUTOGENERATED##########
#include "fcsModel.h"


typedef struct fcsModel::ExtY_fcsModel_T FcsOutput;


struct DataFields{

	// Time it took for the EKF to run
	float dt_s;
	// GPS Time if available
	float time_of_week_ms;
	// Raw Sensor Data (Mag is calibrated and normalized)
	float imu_data[9];
	// GPS NED position and velocity if available;
	float ned_pos_m[3];
	float ned_vel_mps[3];
	// Baro Data
	float baro_data[11];
	//Voltage and current data
	float adc_data[2];
	// Current EKF State
	float ekf_current_state[16];
	// Secondary Filter Debug
	float secondary_filter_debug[3];
	// GPS Valid Flag
	float gps_valid_flag[6];

	// RC In
	float rc_in[7];

	// float actuator commands
	float actuator_cmds[4];

	//Autogenerated fields
	float fcsOut[103];

};

struct __attribute__((packed)) DataFields2{

	// Time it took for the EKF to run
	float dt_s;
	// GPS Time if available
	float time_of_week_ms;
	// Raw Sensor Data (Mag is calibrated and normalized)
	float imu_data[9];
	// Mag Valid Flag
	bool is_mag_valid;
	// GPS position and velocity if available;
	float lat_lon_alt[3];
	float ned_vel_mps[3];
	// GPS Valid Flag
	bool is_gps_valid;
	// Baro Data
	float baro_data[2];
	// Baro Valid Flag
	bool is_baro_valid;
	// Lidar range
	float lidar_range_m;
	bool is_lidar_valid;
	//Voltage and current data
	float adc_data[2];
	// Current EKF State
	float ekf_current_state[23];

	// RC In
	float rc_in[7];

	// float actuator commands
	float actuator_cmds[4];

	//Autogenerated fields
	float fcsOut[103];

};

void AssignFcsData(const FcsOutput &fcs_output, DataFields data_to_save[], size_t data_index);
void AssignFcsData2(const FcsOutput &fcs_output, DataFields2 data_to_save[], size_t data_index);