//#############AUTOGENERATED##########
#include "fcsModel.h"


typedef struct fcsModel::ExtY_fcsModel_T FcsOutput;


struct DataFields{

	// Time it took for the EKF to run
	float dt_s;
	// GPS Time if available
	float time_of_week_ms;
	// Raw Sensor Data (Mag is calibrated and normalized)
	float imu_data[9];
	// GPS NED position and velocity if available;
	float ned_pos_m[3];
	float ned_vel_mps[3];
	// Current EKF State
	float ekf_current_state[16];
	// Secondary Filter Debug
	float secondary_filter_debug[3];
	// GPS Valid Flag
	float gps_valid_flag[6];

	// RC In
	float rc_in[7];

	// float actuator commands
	float actuator_cmds[4];

	//Autogenerated fields
	float fcsOut[43];

};


void AssignFcsData(const FcsOutput &fcs_output, DataFields data_to_save[], size_t data_index);
